%lex

%%

\s+     /* skip white space */

\d+     return 'NUMBER'


/lex


%%

AdditiveExpression
    : AdditiveExpression '+' MultiplicativeExpression
    | MultiplicativeExpression
    ;

MultiplicativeExpression
    : MultiplicativeExpression '*' PrimaryExpression
    | PrimaryExpression
    ;

PrimaryExpression
    : NUMBER
    | '(' AdditiveExpression ')'
    ;